version: "3.4"
services:
  # PHP service
  app:
    build: ./docker/php/.
    container_name: app-php
    working_dir: /var/www/site
    volumes:
      - ./site:/var/www/site
    environment:
      PHP_IDE_CONFIG: "serverName=symfony.cx"
      XDEBUG_CONFIG: "client_host=docker.host.internal"
      XDEBUG_MODE: debug
    networks:
      - app-network

  # Nginx service
  nginx:
    image: nginx:alpine
    container_name: app-nginx
    working_dir: /var/www/site
    ports:
      - 8001:80
    volumes:
      - ./site:/var/www/site
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network

  # Mysql service
  mysql:
    image: mysql:5.7.22
    container_name: app-mysql
    restart: always
    environment:
      - MYSQL_DATABASE=dev
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=app
      - MYSQL_PASSWORD=apppass
    volumes:
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - 8982:3306
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
